project_name: kdiscover

env:
  - GO111MODULE=on

before:
  hooks:
  - go mod download

builds:
  - goos:
    - windows
    - linux
    - darwin
    - freebsd


archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows

source:
  enabled: true

release:
  # If set to true, will not auto-publish the release.
  # TODO(mmicu): disable this after a few tests
  draft: true
  prerelease: auto

changelog:
  skip: false

brews:
  - github:
      owner: mateimicu
      name: homebrew-tap


    commit_author:
      name: goreleaserbot
      email: goreleaser@mateimicu.com

    folder: Formula

    homepage: "https://example.com/"

    description: "Utility for listing and exporting config for K8s Clusters"

    test: |
      system "#{bin}/kdiscover --version"

    install: |
      bin.install "program"
