project_name: kdiscover

env:
  - GO111MODULE=on

before:
  hooks:
  - go mod download

builds:
  - id: general
    goos:
    - windows
    - linux

  - id: macos
    goos:
      - darwin
    goarch:
      - amd64
    hooks:
      post: codesign -s C608BAF5BB825297A907F7F48E06D2028EE37E3F -f -v --timestamp --options runtime ./dist/macos_darwin_amd64/kdiscover

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows

source:
  enabled: true

release:
  # If set to true, will not auto-publish the release.
  # TODO(mmicu): disable this after a few tests
  draft: true
  prerelease: auto

changelog:
  skip: false
