name: Lint & build Golang project

on:
  push
  pull_request
  schedule:
    - cron: "0 8 * * *" # daily

jobs:
  lint:
    name: Go lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.github_token }}

  build:
    name: Go build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
    - name: Start linting
      run: |
        go build main.go
